languageCode = "en-us"
title = "Thoughts2Bits"
baseURL = "https://psuteparuk.github.io/thoughts2bits/"
canonifyURLs = true
copyright = "Copyright &copy; 2019 Thoughts2Bits"
keywords = "Blog, Podcasts, Software, Engineering, Thoughts, Bits"
buildDrafts = true

[params]
  author = "Potcharapol Suteparuk"
  description = "Thoughts2Bits: Software engineering content"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
