languageCode = "en-us"
title = "Thoughts2Bits"
baseURL = "http://thoughts2bits.com/"
canonifyURLs = true
copyright = "Copyright &copy; 2019 Thoughts2Bits"
keywords = "Blog, Engineering, Thoughts, Bits, Thoughts2Bits"

[params]
  author = "Potcharapol Suteparuk"
  description = "Thoughts 2 Bits Blog"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
