languageCode = "en-us"
title = "Thoughts2Bits"
baseurl = "http://thoughts2bits.com/"
canonifyURLs = true
copyright = "Copyright &copy; 2017 Thoughts2Bits"
keywords = "Blog, Engineering, Thoughts, Bits, Thoughts2Bits"

[params]
  author = "Potcharapol Suteparuk"
  description = "Engineering Blog"

[taxonomies]
  category = "categories"
  tag = "tags"
